server:
  address: localhost
  port: 8090

spring:

  # mysql
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

  # redis
  redis:
    host: 127.0.0.1
    port: 6379
    database: 3
    # 布隆过滤器
    bloom:
      expectedInsertions: 100000
      fpp: 0.001

  #   cluster: 192.168.207.10:7001,192.168.207.20:7002,192.168.207.30:7003,192.168.207.10:7004,192.168.207.20:7005,192.168.207.30:7006


# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xishanqu.redislock.mapper
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true



